### ISSUE TITLE
[Synology NAS] No longer working with later versions of Plex

### ISSUE THREAD

**Issue by kratoz29** [origamiofficial/docker-ngrok-plex#1]
This is the what the log throws at me:

```
ngrok url and ip no port = 3.134.39.220
Traceback (most recent call last):
  File "/root/./ngrok-plex.py", line 72, in <module>
    print("Old settings: " + plex.settings.customConnections)
  File "/usr/local/lib/python3.10/site-packages/plexapi/server.py", line 195, in settings
    self._settings = Settings(self, data)
  File "/usr/local/lib/python3.10/site-packages/plexapi/settings.py", line 20, in __init__
    super(Settings, self).__init__(server, data, initpath)
  File "/usr/local/lib/python3.10/site-packages/plexapi/base.py", line 56, in __init__
    self._loadData(data)
  File "/usr/local/lib/python3.10/site-packages/plexapi/settings.py", line 43, in _loadData
    self._settings[id] = Setting(self._server, elem, self._initpath)
  File "/usr/local/lib/python3.10/site-packages/plexapi/base.py", line 56, in __init__
    self._loadData(data)
  File "/usr/local/lib/python3.10/site-packages/plexapi/settings.py", line 119, in _loadData
    self.enumValues = self._getEnumValues(data)
  File "/usr/local/lib/python3.10/site-packages/plexapi/settings.py", line 142, in _getEnumValues
    return {self._cast(k): v for k, v in [kv.split(':') for kv in enumstr.split('|')]}
  File "/usr/local/lib/python3.10/site-packages/plexapi/settings.py", line 142, in <dictcomp>
    return {self._cast(k): v for k, v in [kv.split(':') for kv in enumstr.split('|')]}
ValueError: not enough values to unpack (expected 2, got 1)
```

The issue happens with both Synology DS218+ NAS DSM7 package and the Plexinc version for it, if I rollback to 1.29.0.6244  it works again (it's the latest version that works that I'm aware of).

Greetings!

**Comment by origamiofficial** [comment]
Sorry for the delay as I was working on other project. Try the new version & let me know if the issue is fixed or not. Also note that the container will automatically update every 7 days so this issue shouldn't come near future.

**Comment by kratoz29** [comment]
> @kratoz29 Sorry for the delay as I was working on other project. Try the new version & let me know if the issue is fixed or not. Also note that the container will automatically update every 7 days so this issue shouldn't come near future.

Hi mate, this is the error I'm getting right now:

`Authtoken saved to configuration file: /root/.config/ngrok/ngrok.yml
tWaiting 5 seconds for ngrok to start up
ngrok base url = 4.tcp.ngrok.io
ngrok url and ip no port = 3.129.187.220
Traceback (most recent call last):
  File "/root/./ngrok-plex.py", line 72, in <module>
    print("Old settings: " + plex.settings.customConnections)
                             ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plexapi/server.py", line 195, in settings
    self._settings = Settings(self, data)
                     ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plexapi/settings.py", line 20, in __init__
    super(Settings, self).__init__(server, data, initpath)
  File "/usr/local/lib/python3.11/site-packages/plexapi/base.py", line 56, in __init__
    self._loadData(data)
  File "/usr/local/lib/python3.11/site-packages/plexapi/settings.py", line 43, in _loadData
    self._settings[id] = Setting(self._server, elem, self._initpath)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plexapi/base.py", line 56, in __init__
    self._loadData(data)
  File "/usr/local/lib/python3.11/site-packages/plexapi/settings.py", line 119, in _loadData
    self.enumValues = self._getEnumValues(data)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plexapi/settings.py", line 142, in _getEnumValues
    return {self._cast(k): v for k, v in [kv.split(':') for kv in enumstr.split('|')]}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plexapi/settings.py", line 142, in <dictcomp>
    return {self._cast(k): v for k, v in [kv.split(':') for kv in enumstr.split('|')]}
                                 ^^^^
ValueError: not enough values to unpack (expected 2, got 1)`


Greetings.

**Comment by origamiofficial** [comment]
It seems your previous and latest error messages are the same. I've just tested the latest version of the docker container with my Plex instance which is running the latest PMS version 1.30.0.6486 & it's working !! Maybe you haven't updated the docker container. You've to remove it and redownload again the new docker container. 
To stop the container & remove  it use the below command:
```bash
docker stop $(docker ps -a -q --filter ancestor=rlabinc/ngrok-plex:latest) && docker rm -f $(docker ps -a -q --filter ancestor=rlabinc/ngrok-plex:latest) && docker rmi rlabinc/ngrok-plex:latest
```
This command will first stop any running containers that were created from the "rlabinc/ngrok-plex:latest" image, then it will remove the stopped containers and associated files, and finally, it will remove the "rlabinc/ngrok-plex:latest" image itself. Now try to run the container to download the latest version from the docker hub. I pushed an update to the docker hub the previous day. The PlexAPI needs an update that's why it's not working with the new PMS versions. 
Also, note that the container will automatically update every 7 days so this issue shouldn't come near future. So you've to update every 7 days or so. You can use [Watchtower](https://github.com/containrrr/watchtower) to automate this work for you. I'm not closing the issue, if you need any more help feel free to ask.

**Comment by kratoz29** [comment]
> Hi @kratoz29 It seems your previous and latest error messages are the same. I've just tested the latest version of the docker container with my Plex instance which is running the latest PMS version 1.30.0.6486 & it's working !! Maybe you haven't updated the docker container. You've to remove it and redownload again the new docker container. To stop the container & remove it use the below command:
> 
> ```shell
> docker stop $(docker ps -a -q --filter ancestor=rlabinc/ngrok-plex:latest) && docker rm -f $(docker ps -a -q --filter ancestor=rlabinc/ngrok-plex:latest) && docker rmi rlabinc/ngrok-plex:latest
> ```
> 
> This command will first stop any running containers that were created from the "rlabinc/ngrok-plex:latest" image, then it will remove the stopped containers and associated files, and finally, it will remove the "rlabinc/ngrok-plex:latest" image itself. Now try to run the container to download the latest version from the docker hub. I pushed an update to the docker hub the previous day. The PlexAPI needs an update that's why it's not working with the new PMS versions. Also, note that the container will automatically update every 7 days so this issue shouldn't come near future. So you've to update every 7 days or so. You can use [Watchtower](https://github.com/containrrr/watchtower) to automate this work for you. I'm not closing the issue, if you need any more help feel free to ask.

Hi, I made sure to update the container with the command you gave me but still no luck, I'm running the docker container version from Plexinc in my Synology NAS using the version 1.30.1.6497 and using the DSM package with the version 1.30.0.6486 gives me the same result, strangely enough using the PMS of my Nvidia Shield TV which has the version 1.30.0.6486 works as expected....

Would it be some permission issue with the Synology NAS? 

The error prompted is the same:

`Authtoken saved to configuration file: /root/.config/ngrok/ngrok.yml
Waiting 5 seconds for ngrok to start up
ngrok base url = 8.tcp.ngrok.io
ngrok url and ip no port = 3.142.81.166
Traceback (most recent call last):
  File "/root/./ngrok-plex.py", line 72, in <module>
    print("Old settings: " + plex.settings.customConnections)
                             ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plexapi/server.py", line 195, in settings
    self._settings = Settings(self, data)
                     ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plexapi/settings.py", line 20, in __init__
    super(Settings, self).__init__(server, data, initpath)
  File "/usr/local/lib/python3.11/site-packages/plexapi/base.py", line 56, in __init__
    self._loadData(data)
  File "/usr/local/lib/python3.11/site-packages/plexapi/settings.py", line 43, in _loadData
    self._settings[id] = Setting(self._server, elem, self._initpath)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plexapi/base.py", line 56, in __init__
    self._loadData(data)
  File "/usr/local/lib/python3.11/site-packages/plexapi/settings.py", line 119, in _loadData
    self.enumValues = self._getEnumValues(data)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plexapi/settings.py", line 142, in _getEnumValues
    return {self._cast(k): v for k, v in [kv.split(':') for kv in enumstr.split('|')]}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plexapi/settings.py", line 142, in <dictcomp>
    return {self._cast(k): v for k, v in [kv.split(':') for kv in enumstr.split('|')]}
                                 ^^^^
ValueError: not enough values to unpack (expected 2, got 1)`

**Comment by origamiofficial** [comment]
@kratoz29 I don't use the Synology NAS or neither the Docker version of Plex. So can't confirm what is exactly causing this issue. My exam is knocking so can't try to test with the docker version of PMS right now. But for sure, the issue is related to PlexAPI and the script using it to set new `Custom server access URLs` value. You can use the below checklist to see if anything you're putting there wrong:
* PLEX_BaseURL
* PLEX_Token
Also, send me which value you're putting on `PLEX_BaseURL`.
If you're putting everything right then you should create an issue [HERE](https://github.com/pkkid/python-plexapi) with logs also don't forget to mention the script link below which causing this error. Your first log seems clean, use that one.
Script link:
```bash
https://github.com/origamiofficial/docker-ngrok-plex/blob/main/ngrok-plex.py
```

**Comment by origamiofficial** [comment]
Hi @kratoz29 , I've tested with the latest docker images of PMS & it's working too. Maybe you're putting something wrong there I guess. Can you share your full command to run `ngrok-plex` docker container by replacing the `PLEX_Token` & `NGROK_Token` value as "XXXXXX" ?

**Comment by origamiofficial** [comment]
As there has been no response from @kratoz29  and the container has been verified to work fine on all platforms, I am considering this issue as solved. Feel free to reopen if you need further assistance.

**Comment by kratoz29** [comment]
> As there has been no response from @kratoz29 and the container has been verified to work fine on all platforms, I am considering this issue as solved. Feel free to reopen if you need further assistance.

Hi, sorry for the late response, indeed, just today confirmed that the container is working as expected with the latest version of Plex and the docker container, many thanks for your work!
